Move the clearing of indirect arguments to a seperate pass
GPUOpen-Effects/GeometryFX pull request #8
Opened 2018-09-26 16:30 UTC by ashleysmithgpu

The order of execution of FilterCS() within a Dispatch() is not determinate, so we need to run the clear in a previous pass.

2018-09-26 16:42 UTC, Anteru requested changes
The .inc files needs to get updated as well (by compiling the shader and re-generating the header.)

2018-09-26 16:42 UTC, Anteru commented on amd_geometryfx/src/AMD_GeometryFX_Filtering.cpp
> +        if (currentBatchCount_ > 1)
What does this bit do? That seems wrong.

2018-09-27 09:15 UTC, ashleysmithgpu commented
Updated the shader .inc files as requested, the extra dispatch was an accidental commit from me testing some code, apologies for that.

2018-09-27 10:50 UTC, merged

2018-09-27 10:50 UTC, Anteru commented
Thanks a lot for the quick turnaround on the changes!